language: java
jdk:
- openjdk11

env:
  global:
  - secure: "EABJwCzHLWWcJZnNXWLp6VQN9mq7vHFz/Q510e+iA5g0nkJbZNrd946D/BoMyad0nj5wJ6ocbr/rNW0Pm4bZg8McYoxR1U/hDhkZcBPkAydzXKYYl9dKu0hnOjD5Q+9oaSjjfYWt5eKYTOUh/08rx1W8WFcsw5m2vCDr9uvCRxEBq0aociYGJStqVojTge2pDXstI143u/+O7U1X4+uZF6kmnmzm9lJqCJ4llh+V6nOUMIvDmpzKRVqMmMSUA4Ax/7XPVd6qpWtUoqOF/JxYVmavtIm3rOBoN4PuUKG8U9STaP2/SWigvToY1pfxLKTsNmLfuo1gOEmHppOinP34ds+lgttd77kHqi7hTpOjf3K4EZWcUMuFqh0rwYIxTuv4I2RtE7j1BxYqDeaDSTnyCXeMa96PNhJptzk964fZNXc+e/SxK+eY3SX1F63ITC6M8FLC1YdZfFjxOc4TVktvSDEquMwS2YrT/dIRx8D9u9eFMBNdT/VY17PvqSW2c2onS7n3Zc/qgm9inN2NlzvQ1dEDJP/YW/gvISLadZKGZNIzRhtcSDLbRmXQIK9QAXI4Rtc7lqMmZ2hXpy4pvdsZH13Ifs5ub1xEHvBHEjz3LkPqPfEiNLX4/B45nvgZjDSsOF/tyg84kcg7FOi/bTHonbY21pHPIHcH/Ji0bfbvHFs="
  - secure: "3M9esrs2MZ0csjj1naexb9FX9JWRgZ/TlnspQCZSIsBOPt3YJm9sM7aHkKW8DhT7eQetvVVG/SspgClawV1hWkiU71GjqoaSn+Am/ZTc3Wt4JTVhFz5WWPGmoVQRbmI5s664GxhNUTEjVBG/cC+4IfWcoQg/+uVC3S4gCE5z5ifCulf4Idfa9SSo8UgW/2XJ8o0vDgNrrYsip+cHuqlVoWJscZ4sF5SBF0pProH4jcYr9BHiz+yNCITOLrchRvPy4RuWqp4KomNbTN2AhZL6yjpZ9fwyuvmB/i19gs7+801jw8e3K+n9aLDOBedeP6v4jaqfAa3TAh0vY1zG+x9eEwPTJHwhMMU5tRty7xnEh1i636uMINBT+vt2McRxzBMGEBrUMTR3VebRh9F21rH5yv6iwQBYqCDHv2sHH2Ax3xptez4ELIlI/HbjChosiju8xMtnCoAyR8lRwbXbizD87qTm9Yn1X+9n7wYZGfrBkICrDsCE0OQ8DwhoX1FdZQg6x75K2DiROPVDdsmXWzjMggLYQjPhDNp8XfTJksT9JtYdhk8Tt8Xj/8W9+VRWX6RR0GpwhwG5juayNwRAbJKhE1on+/SW0YOjttZd3AcAklyhx2e55Dbu4mtZrRIM1pyfQZqswmIXMrDISm2mCb1vPE7QzQ7val3BnBo48YVlwQM="
  - secure: "o+gCro+TcSFKFRq2HmF+hRS882wFxMVO75JXAQIqnWexTSyccu0PW6lq1fB86WDUyr9RLfGrxYcNA8+9XJ9dMnxPR9nGWpTFMVmZlEYuFff7+VCMbKMtpiCb297k8/SKwvZDU4wJ5fwBTJteHtZReSAD3Ikp3IHMcDm3x+FmC0iLKksJnUV0OQUpuMYXIB/+mLtcHxURdhIY1Rv/7sxyWqWl/K8nTszD9/evO4QXNQcLT8UDLi+4pzl4quE/8zy1z3gnGPLMmYFvxy8CZ+odzJNhDk93sH38RFECLitVQrtgIAkJJLVAekAJq6oStlctPSZUCI5asolVHppOLrV2zxcNZgTLL4OQXzNRJKYuqhfFBoaUk2a7nKKVHvacCsmkaf1Y7MPZxdC/BmMsQOh4Sd+oUgGaC6Av+d4CAk81zOoahyf+HQgzpGeiYWZEfjDpTDoL9jbOkDsCRl02m9bVJWdnU9WkJrevuw/heMINJBbAvizTL+WVCDwdrPu3bRTmtu12sMs07mztM5mUvDf/hBZ9zXO0ghJEKeg363iPN8PIUuN26y9FymA+MgXoQOBvD8L6tR42SaaGYBJa0tqRat/JoEAjiK0zm6I7O6EfMInXGYB2PSedVtx6U92QR7ugCTquR6a67RxQzliV+iZPM7GSOUULkgd2v/zXgDRKs2s="
  - secure: "ChLS2lX7Kf0WVJMaFD0Kkg+gMqe29RSkWYtMRNJXABm80YhhM7piQEpsM8PoxsZf/7XycstKCBcdR9R0YzzJkkBKbLWYAVcuSZOqvj/jaxXqfLZx/JL2oxOEl3mHK1qazEWAyCUxd6oRnJjEMFgdhIyEt1GMtlXVsTa65Cazb0PpnuS/RD2OhOn8KQLT9kl3OHigPEFaAXpkKht1xSyNxWHAF7dQy2iU/bOx6EfiwAwqDUCmYEso17sgOMwGTWfZaIm8JR67qT2upJv7ZGn/4Lzkn5t1wj5Bix2+YEnYxwsl5pWbCjaAIU9wrVdL3EVrW5/PxKBaGRrg5Sqw3vrIy2QaIGV3RkC8AENdoqmQRa9V0+dSlcN5LrYHq0sPDFk6lieKfF4fcqeTbcClfFsutuCQz6x3taTgst81nkuEzDFhz0pVpW5HrMGY50KJJ4HcvHf+wQYB/rV1NsQb82vTGwFr8GmfLKS8QtV1+oZ1xfdko4lQkO8WjZKY13PouP7b2rVoZW4L4/LayfDaC8T3teFlhfNpbmAk5vM90C3OEj1nGkj3+6gCeaY3bw8sawmoy1j7K7UyeWKSFXs68bBt48LVVgyyawYu3DbMZ7ylnwEDbxGwBuYQE1frKkUkGCHXBNODUnuRWG/AqB0Heol2sMWt69sc/VSlFW4p3kBUsUY="

jobs:
  include:
    # This job is for running testing against feature pull requests to ensure tests are passing. It also serves as a pre req to deploying.
    - stage: test
      name: 'Run testing'
      install: true
      script:
        - mvn test

    # This job is for deploys to maven central using conventional commits. This job should only run against the master branch when it detects a merge. It should also not execute against forked repos.
    - stage: deploy
      name: 'Deploy to Maven Central'
      if: branch = master AND NOT type = pull_request
      install: true
      before_script:
        - openssl aes-256-cbc -K $encrypted_906cef29eab6_key -iv $encrypted_906cef29eab6_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xf secrets.tar --directory deploy/
        - nvm install node
        - nvm use node
        - node --version
      script: bash deploy/deploy.sh
